### ISSUE TITLE
Typed tabs are ignored in XUICodeEditorDemo

### ISSUE THREAD

**Issue by richardklingler** [gkjpettet/XUI#9]
When pasting text into the XUICodeEditorDemo they are displayed fine.
But when typing and inserting a tab, the tab is ignored.

Also the "Spaces per Tab" value is ignored, it is always fixed to 4 regardless what is entered.

**Comment by gkjpettet** [comment]
This code editor is no longer supported. Please use `SyntaxArea` instead.

https://github.com/gkjpettet/SyntaxArea
